### ISSUE TITLE
vim里面能输入中文吗？

### ISSUE THREAD

**Issue by delock** [breathiness/learn-termux#2]
发现在vim里输入中文显示为乱码。保存后在命令行cat时能看见中文。请问vim需要做什么样的设置？

**Comment by delock** [comment]
发现是vim本身设置的问题，不是termux的问题。

**Comment by jzlint** [comment]
vim .vimrc
添加内容如下:
set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
set enc=utf8
set fencs=utf8,gbk,gb2312,gb18030
